
server:
  context-path: /api

---

spring:
  profiles: dev

  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/calypso_local_db?useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy


---

spring:
  profiles: product





---
spring:
  profiles: test
